### ISSUE TITLE
Compiling the flasher

### ISSUE THREAD

**Issue by Manawyrm** [balrog-kun/lights#3]
Hi,

I'm currently having trouble trying to compile the code.
A "make flasher" command returns this message: 
`/usr/avr/include/avr/io.h:530:6: warning: #warning "device type not defined" [-Wcpp]`
followed by a lot of error messages. 

Are you using the arduino toolchain (make, avr-gcc, avr-ld) or the one provided by your operating system? 

I am using the avr-gcc supplied with arch-linux. 

Thanks,
Tobias

**Comment by benchuk** [comment]
same problem using MAC machine.

**Comment by balrog-kun** [comment]
Please try "make flasher.hex" or "make passthrough.hex".  I just checked that "make flasher" doesn't work for me either, but we probably don't want produce a file named "flasher" to avoid confusion between host executables and AVR cross-compiled elf files.

For some reason I wasn't seeing any email notifications for these issues until today...
